from metamenth.enumerations.abstract_enum import AbstractEnum


class MaterialType(AbstractEnum):
    """
    Different materials a layer in a building cover can be made of

    Author: Peter Yefi
    Email: peteryefi@gmail.com
    """
    WOOD = "Wood"
    BRICK = "Brick"
    CONCRETE = "Concrete"
    CONCRETE_BLOCK = "ConcreteBlock"
    VARNISHED_CONCRETE_BLOCK = "VarnishedConcreteBlock"
    STEEL = "Steel"
    ALUMINIUM = "Aluminium"
    FIBRE_CEMENT = "FibreCement"
    GYPSUM_BOARD = "GypsumBoard"
    VEGETATION = "Vegetation"
    COPPER = "Copper"
    ZINC = "Zinc"
    TIN = "Tin"
    STAINLESS_STEEL = "StainlessSteel"
    STONE_COATED_STEEL = "StoneCoatedSteel"
    METAL_SHINGLES = "MetalShingles"
    CONCRETE_TILE = "ConcreteTiles"
    GREEN = "Green"
    ETHYLENE_PROPYLENE_DIENE_MONOMER = "EthylenePropyleneDieneMonomer"
    VINYL = "Vinyl"
    GLASS = "Glass"
    FIBREGLASS = "Fibreglass"
    WINDOW_GAS = "WindowGas"
    GLAZING = "Glazing"
    FIRE_PROOF_GYPSUM_BOARD = "WallFireProofGypsumBoard"
    ORDINARY_GYPSUM_BOARD = "WallOrdinaryGypsumBoard"
    AIR_GAP = "AirGap"
    CELLULOSE = "Cellulose"
    SPRAY_FOAM = "SprayFoam"
    MINERAL_WOOL = "MineralWool"
    SEMI_RIGID_INSULATION = "SemiRigidInsulation"
    FIBREGLASS_INSULATION = "FibreglassInsulation"
    INSULATION = "Insulation"
    METALLIC_STUD = "MetallicStud"
    CERAMIC_TILE = "CeramicTile"
    NATURAL_STONE = "NaturalStone"
    BAMBOO = "Bamboo"
    CORK = "Cork"
    RUBBER = "Rubber"
    LINOLEUM = "Linoleum"
    CRUSHED_STONE_BALLAST = "CrushedStoneBallast"
    RIGID_INSULATION = "RigidInsulation"
    EXTRUDED_POLYSTYRENE = "ExtrudedPolystyrene"
    EXPANDED_POLYSTYRENE = "ExpandedPolystyrene"
    POLYISOCYANURATE = "Polyisocyanurate"
    RUBBER_MEMBRANE = "RubberMembrane"
    POLYVINYL_CHLORIDE = "PolyvinylChloride"
    THERMOPLASTIC_POLYOLEFIN = "ThermoplasticPolyolefin"
    BUTYL_RUBBER = "ButylRubber"
    OTHER = "Other"
